include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = ArizonaPrefs

ArizonaPrefs_FILES = ArizonaRootListController.m
ArizonaPrefs_CFLAGS = -fobjc-arc
ArizonaPrefs_FRAMEWORKS = UIKit
ArizonaPrefs_PRIVATE_FRAMEWORKS = Preferences OnBoardingKit
ArizonaPrefs_INSTALL_PATH = /Library/PreferenceBundles

include $(THEOS_MAKE_PATH)/bundle.mk